##:kivy

#:import rgba kivy.utils.get_color_from_hex

<MusicListWithDropdown>
    IconLeftWidget:
        icon: root.left_icon

    IconRightWidget:
        icon: root.right_icon
        id: music_list_icon_right

        on_press:
            root.open_menu()

        MDLabel:
            size_hint: (None, .8)
            theme_text_color: 'Custom'
            text_color: rgba('#92a3ab')
            text: root.right_text
